# Generated by Django 4.0 on 2021-12-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Compyter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('pamyat', models.FloatField(verbose_name='Pamyat operativniy')),
                ('ekran', models.CharField(max_length=200)),
                ('ozu', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('genre', models.ManyToManyField(to='coputer.Cotegory')),
            ],
            options={
                'db_table': 'Computer',
            },
        ),
    ]
