# Generated by Django 4.0 on 2021-12-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coputer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compyter',
            name='color',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
